// <auto-generated />
using System;
using KamenRiderCardGame.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KamenRiderCardGame.Migrations
{
    [DbContext(typeof(KamenRiderCardGameContext))]
    [Migration("20240921155253_update-character-seeding")]
    partial class updatecharacterseeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KamenRiderCardGame.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Character");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Attack = 10,
                            Avatar = "OOO.png",
                            Deleted = false,
                            Health = 100,
                            Name = "OOO"
                        },
                        new
                        {
                            Id = 2,
                            Attack = 10,
                            Avatar = "Ex-Aid.png",
                            Deleted = false,
                            Health = 100,
                            Name = "Ex-Aid"
                        },
                        new
                        {
                            Id = 3,
                            Attack = 10,
                            Avatar = "Gavv.png",
                            Deleted = false,
                            Health = 100,
                            Name = "Gavv"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
