// <auto-generated />
using System;
using KamenRiderCardGame.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KamenRiderCardGame.Migrations
{
    [DbContext(typeof(KamenRiderCardGameContext))]
    partial class KamenRiderCardGameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SharedResource.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int>("Kick")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Character");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Attack = 10,
                            Avatar = "images/OOO.png",
                            Deleted = false,
                            Description = "OOO",
                            Health = 100,
                            Kick = 10,
                            Name = "OOO",
                            Speed = 10
                        },
                        new
                        {
                            Id = 2,
                            Attack = 10,
                            Avatar = "images/Ex-Aid.png",
                            Deleted = false,
                            Description = "Ex-Aid",
                            Health = 100,
                            Kick = 10,
                            Name = "Ex-Aid",
                            Speed = 10
                        },
                        new
                        {
                            Id = 3,
                            Attack = 10,
                            Avatar = "images/Gavv.png",
                            Deleted = false,
                            Description = "Gavv",
                            Health = 100,
                            Kick = 10,
                            Name = "Gavv",
                            Speed = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
